# Generated by Django 6.0.3 on 2026-03-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(max_length=300, upload_to='produtos/'),
        ),
    ]
